DROP TABLE IF EXISTS listing CASCADE;

CREATE TABLE listings (
    id SERIAL PRIMARY KEY NOT NULL,
    publish_date DATE NOT NULL,
    adoptable BOOLEAN NOT NULL DEFAULT FALSE,
    admin_id INT REFERENCES admins(id) ON DELETE CASCADE,
    dog_id INT REFERENCES dogs(id) ON DELETE CASCADE
);
