DROP TABLE IF EXISTS admin CASCADE;

CREATE TABLE admins (
    id SERIAL PRIMARY KEY NOT NULL,
    rescuer VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);